version: "3"

services:
  nwaf-dyn:
    image: nemesida/nwaf-dyn
    container_name: nwaf-dyn
    ports:
      - 80:80
      - 5672:5672
      - 5673:5673
    volumes:
      - /opt/nwaf/waf-config:/nginx.configs

  nwaf-mlc:
    image: nemesida/nwaf-mlc
    container_name: nwaf-mlc
    volumes:
      - /opt/nwaf/mlc-config:/nwaf_mlc.configs

  PostgreSQL:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    volumes:
      - /opt/nwaf/nwaf-db:/var/lib/postgresql/data
      
  nwaf-api:
    image: nemesida/nwaf-api
    container_name: nwaf-api
    ports:
      - 8080:8080
    volumes:
      - /opt/nwaf/nwaf-api:/nwaf-api

  nwaf-cabinet:
    image: nemesida/nwaf-cabinet
    container_name: nwaf-cabinet
    ports:
      - 8090:80
    volumes:
      - /opt/nwaf/nwaf-cabinet:/nwaf-cabinet
      
  nwaf-scanner:
    image: nemesida/nwaf-scanner
    container_name: nwaf-scanner
    volumes:
      - /opt/nwaf/nwaf-scanner:/nwaf-scanner
