version: "3"

services:
  nwaf-dyn:
    image: nemesida/nwaf-dyn
    container_name: nwaf-dyn
    ports:
      - 80:80
      - 5672:5672
    volumes:
      - /opt/nwaf/waf-config:/nginx.configs

  nwaf-mlc:
    image: nemesida/nwaf-mlc
    container_name: nwaf-mlc
    volumes:
      - /opt/nwaf/mlc-config:/nwaf_mlc.configs

  nwaf-api:
    image: nemesida/nwaf-api
    container_name: nwaf-api
    ports:
      - 8080:8080
    volumes:
      - /opt/nwaf/nwaf-api:/nwaf-api

  nwaf-cabinet:
    image: nemesida/nwaf-cabinet
    container_name: nwaf-cabinet
    ports:
      - 8090:80
    volumes:
      - /opt/nwaf/nwaf-cabinet:/nwaf-cabinet
