version: "3"

services:
  nwaf-dyn:
    image: nemesida/nwaf-dyn
    container_name: nwaf-dyn
    ports:
      - 80:80
      - 5672:5672
    volumes:
      - /opt/nwaf/waf-config:/nginx.configs

  nwaf-mlc:
    image: nemesida/nwaf-mlc
    container_name: nwaf-mlc
    volumes:
      - /opt/nwaf/mlc-config:/nwaf_mlc.configs

  nwaf-web:
    image: nemesida/nwaf-web
    container_name: nwaf-web
    ports:
      - 8080:8080
      - 8090:80
    volumes:
      - /opt/nwaf/api-cab-config:/nwaf-api
      - /opt/nwaf/api-cab-base:/var/lib/postgresql
      
